name: nutpie
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.11
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - statsmodels
  - numba
  - bambi
  - pip
  - nutpie
